### ISSUE TITLE
how to select alpha and beta values from ABneutral output

### ISSUE THREAD

**Issue by ktang** [jlab-code/AlphaBeta#2]
I ran the sample codes with Nstarts = 50 as:

###############
library(AlphaBeta);
inFile <- readRDS(system.file("extdata/dm/","output.rds", package="AlphaBeta"));
pedigree <- inFile$Pdata;
p0uu_in <- inFile$tmpp0;
eqp.weight <- 1;
Nstarts <- 50;
out.name <- "CG_global_estimates_ABneutral";
out <- ABneutral(pedigree.data = pedigree,
                  p0uu=p0uu_in,
                  eqp=p0uu_in,
                  eqp.weight=eqp.weight,
                  Nstarts=Nstarts,
                  out.dir=getwd(),
                  out.name=out.name)
#########################
The whole output is at
[CG_global_estimates_ABneutral.Rdata.txt](https://github.com/jlab-code/AlphaBeta/files/6362156/CG_global_estimates_ABneutral.Rdata.txt)

The first two columns of out$estimates is pasted at the end. I was wondering which alpha/beta values should be reported in a manuscript:

the first row of the result:
Nelder-Mead14    8.613096e-05 2.500105e-04

or 

the reported last qualified iteration, here is
Nelder-Mead48    1.153486e-04 3.350351e-04

or

some other row?

Thanks a lot!

---------------------------
> out$estimates[,1:2]
                        alpha         beta
Nelder-Mead14    8.613096e-05 2.500105e-04
Nelder-Mead37    8.556837e-05 2.483748e-04
Nelder-Mead6     8.045752e-05 2.335199e-04
Nelder-Mead30    9.097679e-05 2.640810e-04
Nelder-Mead16    8.441008e-05 2.449441e-04
Nelder-Mead39    7.611140e-05 2.207919e-04
Nelder-Mead44    9.691734e-05 2.813793e-04
Nelder-Mead17    6.796482e-05 1.972372e-04
Nelder-Mead10    9.954876e-05 2.890216e-04
Nelder-Mead34    1.029701e-04 2.989850e-04
Nelder-Mead22    8.550823e-05 2.482096e-04
Nelder-Mead26    1.044966e-04 3.034201e-04
Nelder-Mead20    6.604412e-05 1.916456e-04
Nelder-Mead31    8.698955e-05 2.521294e-04
Nelder-Mead45    1.106392e-04 3.212895e-04
Nelder-Mead      5.892448e-05 1.709664e-04
Nelder-Mead48    1.153486e-04 3.350351e-04
Nelder-Mead3     1.037350e-04 3.011848e-04
Nelder-Mead23    5.605930e-05 1.626320e-04
Nelder-Mead9     9.453905e-05 2.745014e-04
Nelder-Mead47    5.270097e-05 1.528930e-04
Nelder-Mead35    3.693118e-05 1.071166e-04
Nelder-Mead28    4.825938e-05 1.399961e-04
Nelder-Mead24    9.619632e-05 2.792981e-04
Nelder-Mead13    4.652241e-05 1.349619e-04
Nelder-Mead41    3.171332e-05 9.198640e-05
Nelder-Mead11    3.093550e-05 8.972726e-05
Nelder-Mead43    1.719012e-05 4.983860e-05
Nelder-Mead2     1.687714e-05 4.893920e-05
Nelder-Mead4     5.641535e-05 1.637010e-04
Nelder-Mead40    3.546228e-06 1.028226e-05
Nelder-Mead18    2.335803e-05 6.772142e-05
Nelder-Mead8     4.133407e-05 1.198787e-04
Nelder-Mead15    1.071769e-05 3.107231e-05
Nelder-Mead32    1.356229e-05 3.931142e-05
Nelder-Mead33    2.054148e-05 5.956454e-05
Nelder-Mead42    4.629203e-07 1.342208e-06
Nelder-Mead14.1  8.613096e-05 2.500105e-04
Nelder-Mead14.2  8.613096e-05 2.500105e-04

**Comment by rashmihazarika** [comment]
Thanks for your interest. You should select the first alpha and beta estimates (first row), as the estimates are ordered from best fitting to worst fitting results based on the different starting values. However, please do check if the values in the first row are approximately similar to those in the subsequent rows. If yes, it tells you that the solutions have converged to similar global optima, regardless of starting values.  If you have further question, please let us know.

**Comment by ktang** [comment]
Thanks a lot for your reply:)
